In [1]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3]])
data

a  1    2.163467
   2    1.262077
   3    0.239469
b  1    0.926306
   2   -0.057974
c  3   -0.600766
   1   -1.568808
d  2   -0.683337
   3    0.654906
dtype: float64

In [2]:
data1 = data.unstack()
data1

          1         2         3
a  2.163467  1.262077  0.239469
b  0.926306 -0.057974       NaN
c -1.568808       NaN -0.600766
d       NaN -0.683337  0.654906

In [3]:
data1.stack()

a  1    2.163467
   2    1.262077
   3    0.239469
b  1    0.926306
   2   -0.057974
   3         NaN
c  1   -1.568808
   2         NaN
   3   -0.600766
d  1         NaN
   2   -0.683337
   3    0.654906
dtype: float64

In [4]:
import numpy as np
import pandas as pd

frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1', 'key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [5]:
frame1 = frame.stack(['顏色','縣市'])
frame1

key1  key2  顏色     縣市
a     1     Green  台北     0
            Red    台北     1
            Green  台中     2
      2     Green  台北     3
            Red    台北     4
            Green  台中     5
b     1     Green  台北     6
            Red    台北     7
            Green  台中     8
      2     Green  台北     9
            Red    台北    10
            Green  台中    11
dtype: int64

In [6]:
frame1.unstack('key1')

key1           a   b
key2 顏色    縣市
1    Green 台中  2   8
           台北  0   6
     Red   台北  1   7
2    Green 台中  5  11
           台北  3   9
     Red   台北  4  10

In [8]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a'],
                  'key2':['one', 'two', 'one', 'two', 'one'],
                  'data1': np.random.randn(5),
                  'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one -0.228142  0.174993
1    a  two  0.772909 -0.501651
2    b  one  1.071437 -0.111361
3    b  two  0.953829 -1.562372
4    a  one  0.457435  0.524502

In [9]:
df.groupby('key1').sum()

           key2     data1     data2
key1
a     onetwoone  1.002202  0.197844
b        onetwo  2.025266 -1.673733

In [10]:
df[['key1','data1','data2']].groupby('key1').mean()

         data1     data2
key1
a     0.334067  0.065948
b     1.012633 -0.836867

In [11]:
df1 = df.groupby(['key1','key2']).sum()
df1.columns.name = "data"
df1

data          data1     data2
key1 key2
a    one   0.229293  0.699495
     two   0.772909 -0.501651
b    one   1.071437 -0.111361
     two   0.953829 -1.562372

In [12]:

df1.stack().unstack(['key1','data'])

key1         a                   b
data     data1     data2     data1     data2
key2
one   0.229293  0.699495  1.071437 -0.111361
two   0.772909 -0.501651  0.953829 -1.562372