In [ ]:
# 如何清理資料

import pandas as pd

# 讀檔
dataFram = pd.read_csv('各鄉鎮市區人口密度.csv')
# 每一欄型態
# print(dataFram.dtypes)

# 有多少列
print(len(dataFram))
# 資訊
# dataFram.info()         

# 改變欄位名稱
dataFram.columns = ["統計年", "區域別", "年底人口數", "土地面積", "人口密度"]
# 另一改名稱方法： 
# dataFram.rename(columns=[])

#移除第0列
df = dataFram.drop(index=0)

# 清除所有有NaN的列
df1 = df.dropna()

# 移除統建年欄位 axis=1代表欄, axis=0代表列
df2 = df1.drop('統計年', axis=1)

# 將欄的型態改變
# 強制轉換為數字，非數字無法轉的會變成NaN
df2["年底人口數"] = pd.to_numeric(df2["年底人口數"], errors="coerce")

# 依年底人口數據將NaN的列都去掉
df2 = df2.dropna(subset=["年底人口數"])

# 轉為整數、浮點數
df2["年底人口數"] = df2["年底人口數"].astype("int64")
df2["土地面積"] = df2["土地面積"].astype("float")
df2["人口密度"] = df2["人口密度"].astype("int64")
df2.info()
df2

376
<class 'pandas.DataFrame'>
RangeIndex: 368 entries, 1 to 368
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     368 non-null    str
 1   年底人口數   368 non-null    int64
 2   土地面積    368 non-null    float64
 3   人口密度    368 non-null    int64
dtypes: float64(1), int64(2), str(1)
memory usage: 18.1 KB

        區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484  16.3170  23747
3    新北市中和區  413590  20.1440  20532
4    新北市永和區  222585   5.7138  38956
5    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
364  金門縣烏坵鄉     685   1.2000    571
365  連江縣南竿鄉    7544  10.4000    725
366  連江縣北竿鄉    2360   9.9000    238
367  連江縣莒光鄉    1624   4.7000    346
368  連江縣東引鄉    1352   3.8000    356

[368 rows x 4 columns]

In [39]:
import pandas as pd
import numpy as np

# 讀取 CSV 檔
dataFrame = pd.read_csv('各班圖書借閱統計.csv')

# 第 0 列(index 為 0)才是真正的中文欄位名稱,把它設為欄位名
# dataFrame.loc[0] 看欄位名稱
dataFrame.columns = dataFrame.loc[0]

# 刪除第 0 列(已經拿來當欄位名,資料中不需要重複)
dataFrame = dataFrame.drop(0)

# 提示:整理後資料最後面有「合計列」與 4 列說明文字要刪掉
# 先印出 dataFrame 看看那些列的 index 是多少
print(dataFrame)

# 請完成:刪除合計列與 4 列說明文字(用 drop,可加 inplace=True)
dataFrame.drop([10, 11, 12, 13, 14], inplace=True)


# 取得目前的列數與欄數
rowCount, columnCount = dataFrame.shape #9,5
dataFrame

# 請完成:把索引重設為從 0 開始的連續編號
# dataFrame.index = ______


# 請完成:只保留「班級」「學生人數」「借閱冊數」三個欄位
# dataFrame1 = dataFrame.reindex(columns=[______])


# print(dataFrame1)

0           統計年    班級 學生人數  借閱冊數 平均每人借閱
1           112  一年甲班   35   420     12
2           112  一年乙班   33   264      8
3           112  一年丙班   34   510     15
4           112  二年甲班   36   288      8
5           112  二年乙班   32   480     15
6           112  二年丙班   35   245      7
7           112  三年甲班   30   600     20
8           112  三年乙班   31   372     12
9           112  三年丙班   33   198      6
10           合計    合計  299  3377   11.3
11   資料來源:學校圖書館   NaN  NaN   NaN    NaN
12  製表日期:112年6月   NaN  NaN   NaN    NaN
13    備註:含寒暑假借閱   NaN  NaN   NaN    NaN
14     本表僅供教學使用   NaN  NaN   NaN    NaN

0  統計年    班級 學生人數 借閱冊數 平均每人借閱
1  112  一年甲班   35  420     12
2  112  一年乙班   33  264      8
3  112  一年丙班   34  510     15
4  112  二年甲班   36  288      8
5  112  二年乙班   32  480     15
6  112  二年丙班   35  245      7
7  112  三年甲班   30  600     20
8  112  三年乙班   31  372     12
9  112  三年丙班   33  198      6